### ISSUE TITLE
How long does it take to get fully trained?

### ISSUE THREAD

**Issue by gxwangupc** [antoalli/Deco#2]
Hi, I have two questions. 1. What GPUs you were using? 2. How long did it take to get fully trained?

**Comment by antoalli** [comment]
Hi! Sorry for the late reply. On our workstation (two Titan RTX GPUs) training the completion model takes about two days (240 epochs, ~36h). For ablation experiments we used a v100 based cluster where training time got reduced to 33h.
I noticed that training time increases if using newer PyTorch versions, I'm still in the process of debugging this but in general I strongly advice you to use the suggested environment configuration (torch 1.2).

**Comment by gxwangupc** [comment]
Thank you for your reply and advice.
