### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by Hello-hubKing** [antoalli/Deco#6]
Dear Antonio Alliegro:
I'm very sorry to bother you. I want to ask you to provide the test code.
Best wish to you.

**Comment by antoalli** [comment]
Hi Tan,
We directly test the models during training at each opt.it_test epoch, you can find here the [code](https://github.com/antoalli/Deco/blob/43063bd9db4f5a5df8fe39ea4078908b456be444/train_deco.py#L376) and possibly modify it according to your specific needs. 
Then we just report last training epoch test result averaged across three different seed runs.
Hope to have clarified any doubt,
Antonio

**Comment by Hello-hubKing** [comment]
Thanks for your reply to our request. I ignore the test code in training models.

**Comment by antoalli** [comment]
Don't worry and thanks for the interest in our code. If you have further questions feel free to open another issue.
Antonio
