### ISSUE TITLE
Question About the paper

### ISSUE THREAD

**Issue by zztzzt200** [antoalli/Deco#8]
Hi ! I don't quite understand what 'frame' stands for. 
Could you please tell me something about its function.
Thanks a lot

**Comment by antoalli** [comment]
Hi! With the word "frame" we intend the portion of the input partial point cloud which is around the missing part. 
If you take a look at the right part of the teaser (paper Fig. 1 or the image in this repo) the frame points are the yellow ones.
If you take a look at our architecture in Fig. 2 of the paper you will notice that the decoder works in a hierarchical way: it first predicts a coarse output resembling the frame + the missing part points (Y_fm) and then specializes the prediction to the only missing part (Y_m).
Obviously, this is a regularization strategy we can employ during training for better merging the predicted missing part with the partial input, at test time we simply disregard Y_fm and consider only the missing part prediction Y_m.

See also our paper for a detailed explanation and feel free to ask for more info if something is still unclear,
Antonio

**Comment by zztzzt200** [comment]
Oh! I get it. Figure 1 made me think that the frame was part of the input, which conflicts with the following text and confused me.
I understand now.
Thank you very much.
